### PR TITLE
Update this plugin to Cordova 3.X

### PR DESCRIPTION
**Pull request by orbitaloop**

### CODE REVIEW

**Comment by orbitaloop** [comment]
Hi,
I have updated this plugin for Cordova 3.x. Install is automatic with plugman.
Hope this help,
Cheers,

Sam

PS : All the file structure have changed, that's why it's not possible to merge it automatically.

**Comment by devgeeks** [comment]
I was feeling pretty guilty about not having updated this yet.

Pretty excited to test this out and merge it in.

Thanks soooo much!

**Comment by orbitaloop** [comment]
Thank you for this very useful plugin ;-)

**Comment by devgeeks** [comment]
Thanks so much for that.

Very happy to have this up to 3.0.

**Pull request merged**
